# Generated by Django 4.2.20 on 2025-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
