# Generated by Django 4.2.20 on 2025-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_file_hash_file_reference_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
